### ISSUE TITLE
Brackets extension tests

### ISSUE THREAD

**Issue by khornberg** [dschaffe/brackets-xunit#36]
I am developing a brackets extension and thought that this might run my tests. I know can I go to Debug->Run Tests. I just thought that I would be able to run the tests in my `unittests.js` file as a `unittests` folder is created when selected.

Given the [Simple Brackets Extension](https://github.com/adobe/brackets/wiki/Extension%20Unit%20Tests) example, xunit recognizes that the file has Jasmine tests; when I right click on the file I get a `Run Jasmine xunit Test`. However, when I do so, nothing happens and I'm told there are no tests on the status bar. 

If I just have a file that starts with describe, xunit recognizes it, runs the tests but they fail because they are not set up. Maybe, I'm just doing something wrong...

**Comment by digiguru** [comment]
Does this work for you?

``` javascript
function helloWorld() {
    return "Hello";   
}
describe("Hello world", function () {
    it("says hello", function () {
        expect(helloWorld()).toBe("Hi");
    });
});
```

**Comment by khornberg** [comment]
It does.
How do I load a module then?
If I add `define(function (require, exports, module) { <load module> });` it causes blank output in the xunit window.

**Comment by Wikunia** [comment]
@khornberg did you find a why to test your extensions? I would like to use this extension for the same thing and it doesn't work for me :/

**Comment by digiguru** [comment]
So all this really needs is to see if the current file is unittests.js and if so run...

SpecRunnerUtils.createTestWindowAndRun();

As per

https://github.com/adobe/brackets/wiki/Extension-Unit-Tests

**Comment by Wikunia** [comment]
I will try it in some days :) Thx!

**Comment by khornberg** [comment]
I was not able to get it to run but I haven't attempted it since then.

Kyle
